version: '3.8'

services:
  # Main Application (Development with SQLite)
  app:
    build: .
    container_name: deadman-app-dev
    environment:
      - DATABASE_URL=sqlite:///./data/deadman_switch.db
      - SECRET_KEY=development-secret-key-not-for-production
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src  # Mount source for development
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
    command: >
      bash -c "
        echo 'Running database migrations...'
        uv run alembic upgrade head
        echo 'Creating admin user...'
        uv run python create_admin.py
        echo 'Starting development server...'
        uv run uvicorn deadman_switch.main:app --host 0.0.0.0 --port 8000 --reload
      "
